#!/bin/bash

# Prosty skrypt tworzenia notatki
# Autor: Radek
set -x
# pobierz datę
date=$(date)
set +x
# pobierz temat
topic="$1"

# nazwa pliku
# filename=~/${topic}notka.txt
# filename=~/"$topic"notka.txt
filename="${HOME}/${topic}notka.txt"

# Zapytaj użytkownika o input
read -p "Twoja notka: " note

echo "$date: $note" >> "$filename"
echo "Notatka '$note' zapisana do pliku $filename"