#!/bin/bash

# Skrypt zmieniający rozszerzenia plików
# Autor: Radek

[[ $# -ne 2 ]] && { echo "Muszą być podane dokładnie 2 argumenty" >&2; exit 1; }


for f in *"$1"; do
    base=$(basename "$f" "$1")
    mv "$f" "${base}$2"
    echo mv "$f" "${base}$2"
done
